-- 採点（提案）に、その点にした理由の覚え書きを持たせる。
--
-- 確定（ScoreDecision.comment）は既に持っているが、確定は1セル1行なので
-- 「誰が、なぜその点を付けたか」は書けない。部分点の理由はその採点者のもので、
-- 粒度は (受験者, 設問, 採点者) ＝ QuestionScore と一致する。
--
-- NULL を持たない（DrawingAnnotation.text と同じ形）。「書いていない」と
-- 「空で書いた」を区別する必要が無く、区別すると読む側が毎回2通りを相手にする。
--
-- 列を足すだけなのでテーブルの作り直しは要らない（RENAME TO を含まないので
-- 子テーブルの外部キーが旧名を指したまま残る問題も起きない）。
ALTER TABLE "QuestionScore" ADD COLUMN "comment" TEXT NOT NULL DEFAULT '';
