-- QuestionScore.cropRegionId に索引を張る。
--
-- SQLite は外部キーに索引を自動で作らない。QuestionScore は3本の FK を持つが、索引が
-- あったのは examStudentId だけで、cropRegionId は素通しだった。採点行を「その設問ぶん」
-- 引くたびに表の全走査になる。
--
-- 効くのは「設問ごとに割って全部引く」場合である。索引が無いと設問の数だけ全走査を
-- 繰り返すので、まとめて1本で引くよりはるかに遅くなる。これが段階70 の前提になる
-- —— 採点の取り直しを「書いた設問1つ」まで狭めると、開くときに設問の数だけ引く。
--
-- 書き込み側は影響を受けない（既存行の照会 `(examStudentId, cropRegionId, userId)` は
-- examStudentId の索引に当たっている）。
CREATE INDEX IF NOT EXISTS "QuestionScore_cropRegionId_idx" ON "QuestionScore"("cropRegionId");
