-- 解答用紙に説明を足す。
--
-- 説明を持っていたのは Exam / Coursework / Grade の3つだけで、解答用紙だけ無かった。
-- 4つの概要ページを同じ項目（名前・日付・説明・タグ）で揃えるために足す。
-- 既存3つと同じ宣言（Prisma で String? ＝ TEXT の nullable・既定値なし）。
--
-- **20260823000000 に同梱しないのは、あちらが既にデータへ適用済みだから。**
-- migrationDeployer は名前だけで適用済みを判定するので、適用済みのファイルへ後から
-- 書き足しても二度と読まれず、その環境にだけ列が無いまま「適用済み」になる
-- （実際にそれが起き、AsbDefinition の読み出しが ColumnNotFound で落ちた）。
-- 別の名前で足せば、適用済みの環境にはこれだけが流れ、新しいDBには2本が順に流れる。
ALTER TABLE "AsbDefinition" ADD COLUMN "description" TEXT;
